### ISSUE TITLE
I would like to join this organization.

### ISSUE THREAD

**Issue by JayantGoel001** [Campus-Advisors/campus-advisor-training-irwanphan#10]

**Comment by irwanphan** [comment]
sorry, I don't know where to add you in this repo/org 😥
do you mean the newly created organization for campus & community learning? I can send invitation from there

**Comment by JayantGoel001** [comment]
> sorry, I don't know where to add you in this repo/org 
> do you mean the newly created organization for campus & community learning? I can send invitation from there

I want to get added in this organisation. So basically what I require is a invitation link to this organisation.
